<?php
/**
 * Sample of debugging in PHP
 */

#define custom error handler
function customError ( $error_num , $error_string , $error_file, $error_line, $error_context ) {
	echo "<b>Error number: </b>: [$error_num]<br>";
	echo "<b>Error message: </b>: [$error_string]<br>";
	echo "<b>Error file: </b>: [$error_file]<br>";
	echo "<b>Error line: </b>: [$error_line]<br>";
	echo 'This is generated by Gholam<br>';
	var_dump($error_context);
}


#set error handler as a default error handler
set_error_handler("customError");

$test2 = 20;

#trigger error
//echo $test1;

trigger_error("Gholam ye error bahal dorost kard", E_USER_WARNING);

